apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
spec:
  containers:
  - name: postgres-client
    image: postgres:14
    command: [ "tail", "-f", "/dev/null" ]
    env:
    - name: PGHOST
      value: cloud-sql-proxy-service
    - name: PGDATABASE
      valueFrom:
        secretKeyRef:
          name: database-credentials 
          key: db-name
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          name: database-credentials 
          key: db-user
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: database-credentials 
          key: db-password

# https://stackoverflow.com/a/72649781